//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Titalyver.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400, 600")]
        public global::System.Drawing.Size WindowSize {
            get {
                return ((global::System.Drawing.Size)(this["WindowSize"]));
            }
            set {
                this["WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point WindowPosition {
            get {
                return ((global::System.Drawing.Point)(this["WindowPosition"]));
            }
            set {
                this["WindowPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowInTaskbar {
            get {
                return ((bool)(this["ShowInTaskbar"]));
            }
            set {
                this["ShowInTaskbar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TaskTray {
            get {
                return ((bool)(this["TaskTray"]));
            }
            set {
                this["TaskTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int TimerInterval {
            get {
                return ((int)(this["TimerInterval"]));
            }
            set {
                this["TimerInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ＭＳ ゴシック, 20.25pt")]
        public global::System.Drawing.Font LyricsFont {
            get {
                return ((global::System.Drawing.Font)(this["LyricsFont"]));
            }
            set {
                this["LyricsFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color CurrentColor {
            get {
                return ((global::System.Drawing.Color)(this["CurrentColor"]));
            }
            set {
                this["CurrentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color OtherColor {
            get {
                return ((global::System.Drawing.Color)(this["OtherColor"]));
            }
            set {
                this["OtherColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color BGColor {
            get {
                return ((global::System.Drawing.Color)(this["BGColor"]));
            }
            set {
                this["BGColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color CurrentOutlineColor {
            get {
                return ((global::System.Drawing.Color)(this["CurrentOutlineColor"]));
            }
            set {
                this["CurrentOutlineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color OtherOutlineColor {
            get {
                return ((global::System.Drawing.Color)(this["OtherOutlineColor"]));
            }
            set {
                this["OtherOutlineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public decimal CurrentBackAlpha {
            get {
                return ((decimal)(this["CurrentBackAlpha"]));
            }
            set {
                this["CurrentBackAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGreen")]
        public global::System.Drawing.Color CurrentBackColor {
            get {
                return ((global::System.Drawing.Color)(this["CurrentBackColor"]));
            }
            set {
                this["CurrentBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AntiAlias {
            get {
                return ((bool)(this["AntiAlias"]));
            }
            set {
                this["AntiAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FontOutline {
            get {
                return ((bool)(this["FontOutline"]));
            }
            set {
                this["FontOutline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int FontOutlineSlip {
            get {
                return ((int)(this["FontOutlineSlip"]));
            }
            set {
                this["FontOutlineSlip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContinuousScroll {
            get {
                return ((bool)(this["ContinuousScroll"]));
            }
            set {
                this["ContinuousScroll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public decimal ScrollTime {
            get {
                return ((decimal)(this["ScrollTime"]));
            }
            set {
                this["ScrollTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public decimal FadeTime {
            get {
                return ((decimal)(this["FadeTime"]));
            }
            set {
                this["FadeTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center")]
        public global::System.Drawing.StringAlignment HAlignment {
            get {
                return ((global::System.Drawing.StringAlignment)(this["HAlignment"]));
            }
            set {
                this["HAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center")]
        public global::System.Drawing.StringAlignment VAlignment {
            get {
                return ((global::System.Drawing.StringAlignment)(this["VAlignment"]));
            }
            set {
                this["VAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int YOffset {
            get {
                return ((int)(this["YOffset"]));
            }
            set {
                this["YOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal LineSpace {
            get {
                return ((decimal)(this["LineSpace"]));
            }
            set {
                this["LineSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal CharSpace {
            get {
                return ((decimal)(this["CharSpace"]));
            }
            set {
                this["CharSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal NoRubyPlusSpace {
            get {
                return ((decimal)(this["NoRubyPlusSpace"]));
            }
            set {
                this["NoRubyPlusSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal RubyBottomSpace {
            get {
                return ((decimal)(this["RubyBottomSpace"]));
            }
            set {
                this["RubyBottomSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal TopMargin {
            get {
                return ((decimal)(this["TopMargin"]));
            }
            set {
                this["TopMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal LeftMargin {
            get {
                return ((decimal)(this["LeftMargin"]));
            }
            set {
                this["LeftMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal RightMargin {
            get {
                return ((decimal)(this["RightMargin"]));
            }
            set {
                this["RightMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal BottomMargin {
            get {
                return ((decimal)(this["BottomMargin"]));
            }
            set {
                this["BottomMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("notepad.exe")]
        public string EditorPath {
            get {
                return ((string)(this["EditorPath"]));
            }
            set {
                this["EditorPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"%1\"")]
        public string EditorParam {
            get {
                return ((string)(this["EditorParam"]));
            }
            set {
                this["EditorParam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[00:00.00]%Artist%\r\n[00:00.00]%Title%\r\n[99:59.99]%Album%\r\n[99:59.99]%Date%\r\n[99:5" +
            "9.99]%Comment%\r\n")]
        public string NoLyricsFormat {
            get {
                return ((string)(this["NoLyricsFormat"]));
            }
            set {
                this["NoLyricsFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%FileFolder%%FileName%.kra\r\n%FileFolder%%FileName%.lrc\r\n%FileFolder%%FileName%.tx" +
            "t\r\n")]
        public string LyricsSearchPath {
            get {
                return ((string)(this["LyricsSearchPath"]));
            }
            set {
                this["LyricsSearchPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%FileFolder%*.png\r\n%FileFolder%*.jpg\r\n%ExeFolder%NoImage.png\r\n")]
        public string BGImageSearchPath {
            get {
                return ((string)(this["BGImageSearchPath"]));
            }
            set {
                this["BGImageSearchPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300, 300")]
        public global::System.Drawing.Size BGILimitSize {
            get {
                return ((global::System.Drawing.Size)(this["BGILimitSize"]));
            }
            set {
                this["BGILimitSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal CurrentBackPlusUp {
            get {
                return ((decimal)(this["CurrentBackPlusUp"]));
            }
            set {
                this["CurrentBackPlusUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal CurrentBackPlusDown {
            get {
                return ((decimal)(this["CurrentBackPlusDown"]));
            }
            set {
                this["CurrentBackPlusDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public int BGIFilterAlpha {
            get {
                return ((int)(this["BGIFilterAlpha"]));
            }
            set {
                this["BGIFilterAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color BGIFilterColor {
            get {
                return ((global::System.Drawing.Color)(this["BGIFilterColor"]));
            }
            set {
                this["BGIFilterColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int LyricsLayoutPosition {
            get {
                return ((int)(this["LyricsLayoutPosition"]));
            }
            set {
                this["LyricsLayoutPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LyricsLayoutLeft {
            get {
                return ((int)(this["LyricsLayoutLeft"]));
            }
            set {
                this["LyricsLayoutLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LyricsLayoutTop {
            get {
                return ((int)(this["LyricsLayoutTop"]));
            }
            set {
                this["LyricsLayoutTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LyricsLayoutRight {
            get {
                return ((int)(this["LyricsLayoutRight"]));
            }
            set {
                this["LyricsLayoutRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LyricsLayoutBottom {
            get {
                return ((int)(this["LyricsLayoutBottom"]));
            }
            set {
                this["LyricsLayoutBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int BGILayoutPosition {
            get {
                return ((int)(this["BGILayoutPosition"]));
            }
            set {
                this["BGILayoutPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BGILayoutLeft {
            get {
                return ((int)(this["BGILayoutLeft"]));
            }
            set {
                this["BGILayoutLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BGILayoutTop {
            get {
                return ((int)(this["BGILayoutTop"]));
            }
            set {
                this["BGILayoutTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BGILayoutRight {
            get {
                return ((int)(this["BGILayoutRight"]));
            }
            set {
                this["BGILayoutRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BGILayoutBottom {
            get {
                return ((int)(this["BGILayoutBottom"]));
            }
            set {
                this["BGILayoutBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int BGIPosition {
            get {
                return ((int)(this["BGIPosition"]));
            }
            set {
                this["BGIPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BGILimitDisplayX {
            get {
                return ((bool)(this["BGILimitDisplayX"]));
            }
            set {
                this["BGILimitDisplayX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BGILimitDisplayY {
            get {
                return ((bool)(this["BGILimitDisplayY"]));
            }
            set {
                this["BGILimitDisplayY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BGILimitSourceX {
            get {
                return ((bool)(this["BGILimitSourceX"]));
            }
            set {
                this["BGILimitSourceX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BGILimitSourceY {
            get {
                return ((bool)(this["BGILimitSourceY"]));
            }
            set {
                this["BGILimitSourceY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BGILimitMaxSizeX {
            get {
                return ((bool)(this["BGILimitMaxSizeX"]));
            }
            set {
                this["BGILimitMaxSizeX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BGILimitMaxSizeY {
            get {
                return ((bool)(this["BGILimitMaxSizeY"]));
            }
            set {
                this["BGILimitMaxSizeY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InfoText {
            get {
                return ((string)(this["InfoText"]));
            }
            set {
                this["InfoText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color InfoTextColor {
            get {
                return ((global::System.Drawing.Color)(this["InfoTextColor"]));
            }
            set {
                this["InfoTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InfoTextOutline {
            get {
                return ((bool)(this["InfoTextOutline"]));
            }
            set {
                this["InfoTextOutline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color InfoTextOutlineColor {
            get {
                return ((global::System.Drawing.Color)(this["InfoTextOutlineColor"]));
            }
            set {
                this["InfoTextOutlineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center")]
        public global::System.Drawing.StringAlignment InfoTextHAlignment {
            get {
                return ((global::System.Drawing.StringAlignment)(this["InfoTextHAlignment"]));
            }
            set {
                this["InfoTextHAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Near")]
        public global::System.Drawing.StringAlignment InfoTextVAlignment {
            get {
                return ((global::System.Drawing.StringAlignment)(this["InfoTextVAlignment"]));
            }
            set {
                this["InfoTextVAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int InfoTextLayoutPosition {
            get {
                return ((int)(this["InfoTextLayoutPosition"]));
            }
            set {
                this["InfoTextLayoutPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InfoTextLayoutLeft {
            get {
                return ((int)(this["InfoTextLayoutLeft"]));
            }
            set {
                this["InfoTextLayoutLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InfoTextLayoutTop {
            get {
                return ((int)(this["InfoTextLayoutTop"]));
            }
            set {
                this["InfoTextLayoutTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InfoTextLayoutRight {
            get {
                return ((int)(this["InfoTextLayoutRight"]));
            }
            set {
                this["InfoTextLayoutRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InfoTextLayoutBottom {
            get {
                return ((int)(this["InfoTextLayoutBottom"]));
            }
            set {
                this["InfoTextLayoutBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ＭＳ ゴシック, 15.75pt")]
        public global::System.Drawing.Font InfoTextFont {
            get {
                return ((global::System.Drawing.Font)(this["InfoTextFont"]));
            }
            set {
                this["InfoTextFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int InfoTextOutlineSlip {
            get {
                return ((int)(this["InfoTextOutlineSlip"]));
            }
            set {
                this["InfoTextOutlineSlip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InfoTextAntiAlias {
            get {
                return ((bool)(this["InfoTextAntiAlias"]));
            }
            set {
                this["InfoTextAntiAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 128")]
        public global::System.Drawing.Color StandbyColor {
            get {
                return ((global::System.Drawing.Color)(this["StandbyColor"]));
            }
            set {
                this["StandbyColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color StandbyOutlineColor {
            get {
                return ((global::System.Drawing.Color)(this["StandbyOutlineColor"]));
            }
            set {
                this["StandbyOutlineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KaraokeMode {
            get {
                return ((int)(this["KaraokeMode"]));
            }
            set {
                this["KaraokeMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color NTTTColor {
            get {
                return ((global::System.Drawing.Color)(this["NTTTColor"]));
            }
            set {
                this["NTTTColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color NTTTOutlineColor {
            get {
                return ((global::System.Drawing.Color)(this["NTTTOutlineColor"]));
            }
            set {
                this["NTTTOutlineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KaraokeDisplay {
            get {
                return ((bool)(this["KaraokeDisplay"]));
            }
            set {
                this["KaraokeDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int KaraokeDisplayBottomMargin {
            get {
                return ((int)(this["KaraokeDisplayBottomMargin"]));
            }
            set {
                this["KaraokeDisplayBottomMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KaraokeLastNext {
            get {
                return ((bool)(this["KaraokeLastNext"]));
            }
            set {
                this["KaraokeLastNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public byte BGColorAlpha {
            get {
                return ((byte)(this["BGColorAlpha"]));
            }
            set {
                this["BGColorAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public byte LayeredWindowAlpha {
            get {
                return ((byte)(this["LayeredWindowAlpha"]));
            }
            set {
                this["LayeredWindowAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public byte BGImageAlpha {
            get {
                return ((byte)(this["BGImageAlpha"]));
            }
            set {
                this["BGImageAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FrameImagePath {
            get {
                return ((string)(this["FrameImagePath"]));
            }
            set {
                this["FrameImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Near")]
        public global::System.Drawing.StringAlignment NTTTVAlignment {
            get {
                return ((global::System.Drawing.StringAlignment)(this["NTTTVAlignment"]));
            }
            set {
                this["NTTTVAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NTTTYOffset {
            get {
                return ((int)(this["NTTTYOffset"]));
            }
            set {
                this["NTTTYOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RubyAlignment {
            get {
                return ((int)(this["RubyAlignment"]));
            }
            set {
                this["RubyAlignment"] = value;
            }
        }
    }
}
